export const operatorMapping = {
    vibelog: "Wesley",
    tac: "Wesley",
    simas: "Rubens",
    //Saff--------------------------
    saff_fortaleza: "Wesley",
    saff_porto: "Wesley",
    saff_navegantes: "Wesley",
    saff_ipojuca: "Wesley",
    saff_santos: "Wesley",
    saff_simoes: "Wesley",
    //MWM---------------------------
    mwm: "Maria",
    mvrl: "Maria",
    mvrt: "Maria",
    wagner: "Maria",
    primelog: "Maria",
    itaciba: "Maria",
    toplogmatriz: "Maria",
    toplogfilial: "Maria",
    //------------------------------
    gh: "Laion",
    elo: "Maria",
    dumaszak: "Maria",
    dionizio: "",
    betel: "Laion",
    barcellos: "Luis Felipe",
    froes: "Luis Felipe",
    sanmartino: "Rubens",
    rtm: "Wesley",
    mge: "Rubens",
    lf: "Laion",
    gtl: "Rubens",
    eil: "Marcy",
    comavix: "Luis Felipe",
    beviani: "Wesley",
    bc: "Laion",
    baroncelo: "Rubens",
    aj: "Laion",
    picoli: "Marcy",
    wl: "Laion",
    viplog: "Marcy",
    sudden: "Luis Felipe",
    smlog: "Laion",
    semfronteiras: "Laion",
    werner: "Luis Felipe",
    portolog: "Maria",
    pedrao: "Wesley",
    paganini: "Luis Felipe",
    nardi: "Luis Felipe",
    kobrasol: "Wesley",
    jomar: "Luis Felipe",
    hr: "Marcy",
    gbs: "Marcy",
    fraga: "Luis Felipe",
    transcosta: "Laion",
    evandro: "Luis Felipe",
    comex: "Rubens",
    taype: "Maria"
}